#define GLFW_INCLUDE_NONE
#define STB_IMAGE_IMPLEMENTATION
#include <stdio.h>
#include <stdlib.h>
#include <GLFW/glfw3.h>
#include <GL/glew.h>
#include "include/cglm/cglm.h"
#include "include/stb_image.h"
#include "Buffers.h"
#include "File.h"
#include "Shader.h"
#include "Texture.h"
#include "Camera.h"
#include "Input.h"
